// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://levjmurfpnmsbcxqkepy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldmptdXJmcG5tc2JjeHFrZXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzAzOTYsImV4cCI6MjA2Nzk0NjM5Nn0.bWqvTdNz-NEqmiRnzTODVYl6sKPU2LISzdl80NIoZHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
